name: Deploy to HostingKR

on:
  push:
    branches: [ main ]  # main 브랜치 푸시 시 배포

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. (선택) Node.js 환경 설정 (Vite 같은 빌드 툴 쓸 경우)
      # - name: Setup Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 22
      #
      # - name: Install dependencies
      #   run: npm install
      #
      # - name: Build project
      #   run: npm run build

      # 3. SFTP로 호스팅 서버에 배포
      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: ./   # 배포할 로컬 경로 (현재 루트)
          remote_path: /home/yourdomain/public_html/  # 호스팅KR의 웹 루트 경로
          # 빌드 결과물만 배포할 경우: local_path: ./dist

      # 4. 캐시 무효화를 위해 권한 및 타임스탬프 조정 (선택)
      - name: Clear cache (optional)
        run: echo "Deployed and cache cleared"
